import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css"
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zuai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#ebf6fc] `}>
        <div className="md:grid min-h-[100vh] md:grid-cols-[3rem,1fr] md:px-2 md:py-1">
          <Navbar/>
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
